#!/usr/bin/env python3

# Load modules from $CHARM_DIR/lib
import sys
sys.path.append('lib')

from charms.reactive import (
    main,
    set_state,
    remove_state,
)

from charmhelpers.core.hookenv import action_fail


set_state('vpe.connect-domains')

try:
    main()
except Exception as e:
    action_fail(repr(e))
finally:
    remove_state('vpe.connect-domains')
