#!/usr/bin/env python3
import sys
sys.path.append('lib')

from charms.reactive import main
from charms.reactive import set_state
from charms.reactive import remove_state
from charmhelpers.core.hookenv import action_fail


set_state('vpe.delete-corporation')

try:
    main()
except Exception as e:
    action_fail(repr(e))
finally:
    remove_state('vpe.delete-corporation')
